### ISSUE TITLE
Social link creation

### ISSUE THREAD

**Issue by dulldesk** [KuriusMTL/HackItForward#25]
Users should be able to add and edit social links to their profiles. 

A similar feature would be needed for #16 #17

**Comment by dulldesk** [comment]
Preferably (I would think), the links could be added in the same page as `edit_profile`, or at least a hyperlink from that page to another one.

**Comment by fluix-dev** [comment]
> Preferably (I would think), the links could be added in the same page as edit_profile

Agreed.

**Comment by fluix-dev** [comment]
I think something like [this](https://spiderpig86.github.io/Cirrus/docs/forms/index.html#form_controls) would look nice for editing/creating links:
![image](https://user-images.githubusercontent.com/52835679/93007444-36d29c00-f537-11ea-924d-2ad90a3ae384.png)
