### ISSUE TITLE
Empty challenge start and/or end times yield IntegrityError

### ISSUE THREAD

**Issue by dulldesk** [KuriusMTL/HackItForward#31]
When creating a Challenge in the Django admin interface, if either the Challenge Start or End timestamp (or both) is left empty, an Integrity Error is thrown: 
> IntegrityError at /admin/app/challenge/add/
NOT NULL constraint failed: app_challenge.end *(or app_challenge.start)*

It should be noted that challenge start and end times are blank-able, as defined in [`models.py`](https://github.com/KuriusMTL/stratus/blob/master/app/models.py#L148-L157).

**Comment by fluix-dev** [comment]
They need to be `null`able.
