### ISSUE TITLE
Visit Another User Profile

### ISSUE THREAD

**Issue by Gongsta** [KuriusMTL/HackItForward#57]
If you click on the profile of another user, it is blank.

**Comment by fluix-dev** [comment]
Fixed in c7676ed33d88fe496ea2be36554fc1101fe393ec.

**Comment by Gongsta** [comment]
It doesn't work on the deployed website. It should redirect to the user profile's url, but it simply leads to: https://hackitforward.com/home/4

<img width="1111" alt="Screen Shot 2020-10-01 at 6 42 26 PM" src="https://user-images.githubusercontent.com/43485866/94870580-dcca4580-0415-11eb-8019-816eb464e3c6.png">

This is my own profile information.

**Comment by fluix-dev** [comment]
Ah, interesting.

**Comment by dulldesk** [comment]
~~I am slightly confused, what is the issue? This is what I see for the home page for Gongsta:~~ never mind signed in
![image](https://user-images.githubusercontent.com/54601393/94870804-7c87d380-0416-11eb-8dee-98af89eb126e.png)

https://hackitforward.com/home/4 gives me 
![image](https://user-images.githubusercontent.com/54601393/94870830-8d384980-0416-11eb-9cce-ea4876cf4592.png)

**Comment by Gongsta** [comment]
Yup, so it doesn't work when you are logged in.

Also, can we make it so that the url to a user is their username? Right now, ava's url is 4.. mine is 2. Could we make it so that it is https://hackitforward.com/user/gongsta ?
