### ISSUE TITLE
Cards use raw initiative descriptions

### ISSUE THREAD

**Issue by fredj11** [KuriusMTL/HackItForward#73]
When writing the description of a challenge, there is an option to make text bold, italic, etc. This simply adds asterisks around the modified text but looks fine when on the challenge's page.

When in the list of challenges or the home page however, hovering over a challenge shows the asterisks and not the formatted text

![image](https://user-images.githubusercontent.com/46831504/99861606-94511d80-2b64-11eb-86ca-afcd055c51aa.png)

**Comment by fluix-dev** [comment]
The solution here is probably to strip them entirely. Otherwise, descriptions that start off with headers would look horrible. Repeating myself from other issues, the cards are a real pain to deal with in their current state.

**Comment by fluix-dev** [comment]
Now that I look at this again, we just need to open up the `one_liner` field on the edit/creation forms and have that be used.
