### ISSUE TITLE
Weird UI bug in card description

### ISSUE THREAD

**Issue by fredj11** [KuriusMTL/HackItForward#76]
Text is cut in half for certain cards when hovering over them.
![HackItForward_UI_Bug](https://user-images.githubusercontent.com/46831504/101261589-84117480-3706-11eb-8188-a9aa1c60ecec.gif)

**Comment by fredj11** [comment]
Maybe related : tags cover the title of some challenge names.
![image](https://user-images.githubusercontent.com/46831504/101261632-b622d680-3706-11eb-9494-d178fa96e8e5.png)

**Comment by fluix-dev** [comment]
Yeah, cards are [a mess](https://github.com/KuriusMTL/HackItForward/pull/59#issuecomment-706790232). This should probably be fixed in one of the PRs related to #74 by switching to [static cards](https://spiderpig86.github.io/Cirrus/docs/components/#cards) without animation.

**Comment by Gongsta** [comment]
No longer applicable since cards have a new UI.
