### ISSUE TITLE
Dependency Vulnerability Issue

### ISSUE THREAD

**Issue by MarkChiuu** [KuriusMTL/HackItForward#78]
Following message:
We found potential security vulnerabilities in your dependencies.

You can see this message because you have been granted access to Dependabot alerts for this repository. 

Remediation

Upgrade jinja2 to version 2.11.3 or later. For example: **Medium Severity**
```
jinja2>=2.11.3
```

 Upgrade Pillow to version 8.1.1 or later. For example: **High Severity**
```
Pillow>=8.1.1

```
 Upgrade django to version 3.1.6 or later. For example: **High Severity**
```
django>=3.1.6
```

**Comment by Gongsta** [comment]
Fixed in [commit](https://github.com/KuriusMTL/HackItForward/commit/d52a88657cbcf9348c97cd933310aa9c6d5cc0cd)
