### ISSUE TITLE
Fix Search

### ISSUE THREAD

**Issue by MarkChiuu** [KuriusMTL/HackItForward#83]
Search Bar gives error:

Request Method: | GET
-- | --
http://localhost:8000/?type=challenge&q=em
3.1.7
UndefinedError
'challenges' is undefined
/Users/***/HackItForward/app/templates/explore.html, line 27, in block "body"
/usr/local/opt/python@3.9/bin/python3.9
3.9.1
['/Users/****/HackItForward',  '/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',  '/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9',  '/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages',  '/usr/local/Cellar/protobuf/3.15.5/libexec/lib/python3.9/site-packages']

**Comment by Gongsta** [comment]
Resolved in this [commit](https://github.com/KuriusMTL/HackItForward/commit/78af9aedcfaefdde732623beb39f19a73553a9a5).
