### ISSUE TITLE
SSRF vulnerability

### ISSUE THREAD

**Issue by fluix-dev** [KuriusMTL/HackItForward#94]
Reporting in the public because this got added 1 hour ago and I don't believe this site is deployed publicly.

I'm pretty sure https://github.com/KuriusMTL/HackItForward/pull/93 adds an [SSRF](https://en.wikipedia.org/wiki/Server-side_request_forgery) vulnerability in the [`addUnsplashPicture`](https://github.com/KuriusMTL/HackItForward/blob/a7eadf4e2859b8c3b0887d8343e5b315c8af809c/app/views.py#L472) handler here:

```py
url = request.POST["url"]
url += ".jpg"
response = requests.get(url, stream=True)
```

The url that gets requested here is attacker controlled, with the exception of a forced `.jpg` being added on meaning they could request local content from `127.0.0.1` for example. I'm not actually sure where this view is used, but mitigations could be either only passing along the image ID (like `photo-1547656807-9733c2b738c2`) which gets appended to `https://images.unsplash.com/` or check that the domain is Unsplash. You should also probably use `allow_redirects=False` to prevent any open redirects leading to SSRFs.

**Comment by fluix-dev** [comment]
@Gongsta bump on this because the website appears to be live.

**Comment by Gongsta** [comment]
Fixed in [commit](https://github.com/KuriusMTL/HackItForward/commit/2e1eb5a7155f0d139547c7e3aa9d61df1e0699c5). Thanks!
